<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\BuilderController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CreateController;
use App\Http\Controllers\DriveController;
use App\Http\Controllers\ForumController;
use App\Http\Controllers\ImageStudioController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\StudioController;
use App\Http\Controllers\UniverseController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', [UniverseController::class, 'home'])->name('home');
Route::get('/explore', [UniverseController::class, 'explore'])->name('explore');
Route::get('/create', [CreateController::class, 'form']);
Route::post('/create', [CreateController::class, 'store']);
Route::get('/login', [AuthController::class, 'form']);
Route::post('/login', [AuthController::class, 'login']);
Route::post('/register', [AuthController::class, 'register']);
Route::post('/logout', [AuthController::class, 'logout']);
Route::get('/login/demo', function () {
    $u = User::query()->where('email', 'creator@geniuspace.test')->firstOrFail();
    Auth::login($u);
    return redirect('/')->with('ok', 'Connecté en créateur.');
});
Route::get('/profil/{id?}', [ProfileController::class, 'show']);
Route::post('/profil', [ProfileController::class, 'save']);
Route::post('/profil/playlist', [ProfileController::class, 'playlist']);
Route::post('/profil/pl-add', [ProfileController::class, 'addToPlaylist']);
Route::post('/profil/dm', [ProfileController::class, 'dm']);
Route::get('/pl/{share}', [ProfileController::class, 'playlistShow']);
Route::get('/studio/image', [ImageStudioController::class, 'show']);
Route::post('/studio/image', [ImageStudioController::class, 'save']);
Route::get('/n/{slug}/studio', [StudioController::class, 'show']);
Route::post('/n/{slug}/studio/tab', [StudioController::class, 'tab']);
Route::post('/n/{slug}/studio/cck', [StudioController::class, 'cck']);
Route::post('/n/{slug}/studio/seo', [StudioController::class, 'seo']);
Route::post('/n/{slug}/studio/ats', [StudioController::class, 'ats']);
Route::post('/n/{slug}/studio/weave', [StudioController::class, 'weave']);
Route::post('/n/{slug}/studio/ban', [StudioController::class, 'ban']);
Route::post('/n/{slug}/studio/approve', [StudioController::class, 'approve']);
Route::get('/llm/tools', [BuilderController::class, 'tools']);
Route::get('/builder/{slug?}', [BuilderController::class, 'show']);
Route::get('/builder/{slug}/state', [BuilderController::class, 'state']);
Route::post('/builder/{slug}/bang', [BuilderController::class, 'bang']);
Route::post('/builder/{slug}/compile', [BuilderController::class, 'compile']);
Route::post('/builder/{slug}/add', [BuilderController::class, 'add']);
Route::post('/builder/{slug}/link', [BuilderController::class, 'link']);
Route::post('/builder/{slug}/sync', [BuilderController::class, 'sync']);
Route::post('/builder/{slug}/media', [BuilderController::class, 'media']);
Route::get('/n/{slug}', [UniverseController::class, 'show'])->name('node.show');
Route::get('/n/{slug}/t/{tid}', [UniverseController::class, 'thread'])->name('thread.show');
Route::get('/n/{slug}/p/{pid}', [UniverseController::class, 'product'])->name('product.show');
Route::get('/n/{slug}/v/{vid}', [UniverseController::class, 'video'])->name('video.show');
Route::get('/play', [MediaController::class, 'play'])->name('media.play');
Route::get('/drive', [DriveController::class, 'index'])->name('drive');
Route::post('/drive', [DriveController::class, 'store'])->name('drive.store');
Route::post('/drive/folder', [DriveController::class, 'folder']);
Route::post('/drive/rename', [DriveController::class, 'rename']);
Route::post('/drive/lock', [DriveController::class, 'lock']);
Route::post('/forum', [ForumController::class, 'thread']);
Route::post('/n/{slug}/t/{tid}/reply', [ForumController::class, 'reply']);
Route::post('/n/{slug}/t/{tid}/live', [ForumController::class, 'live']);
Route::post('/n/{slug}/t/{tid}/fire', [ForumController::class, 'fire']);
Route::post('/n/{slug}/t/{tid}/echo', [ForumController::class, 'echoLive']);
Route::post('/n/{slug}/t/{tid}/award', [ForumController::class, 'award']);
Route::post('/n/{slug}/guilde', [ForumController::class, 'guild']);
Route::post('/cart', [CartController::class, 'add'])->name('cart.add');
Route::post('/cart/checkout', [CartController::class, 'checkout'])->name('cart.checkout');
Route::get('/sitemap.xml', function () {
    $nodes = \App\Models\GpNode::all();
    $xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
    foreach ($nodes as $n) {
        $xml .= '<url><loc>'.e(url('/n/'.$n->slug)).'</loc></url>';
    }
    $xml .= '</urlset>';
    return response($xml, 200, ['Content-Type' => 'application/xml']);
});
