/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as NSlugPPidRouteImport } from './routes/n.$slug.p.$pid'
import { Route as NSlugTTidRouteImport } from './routes/n.$slug.t.$tid'
import { Route as NSlugVVidRouteImport } from './routes/n.$slug.v.$vid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugPPidRoute = NSlugPPidRouteImport.update({
  id: '/p/$pid',
  path: '/p/$pid',
  getParentRoute: () => NSlugRoute,
} as any)
const NSlugTTidRoute = NSlugTTidRouteImport.update({
  id: '/t/$tid',
  path: '/t/$tid',
  getParentRoute: () => NSlugRoute,
} as any)
const NSlugVVidRoute = NSlugVVidRouteImport.update({
  id: '/v/$vid',
  path: '/v/$vid',
  getParentRoute: () => NSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/n/$slug/p/$pid': typeof NSlugPPidRoute
  '/n/$slug/t/$tid': typeof NSlugTTidRoute
  '/n/$slug/v/$vid': typeof NSlugVVidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/n/$slug/p/$pid': typeof NSlugPPidRoute
  '/n/$slug/t/$tid': typeof NSlugTTidRoute
  '/n/$slug/v/$vid': typeof NSlugVVidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/n/$slug': typeof NSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/n/$slug/p/$pid': typeof NSlugPPidRoute
  '/n/$slug/t/$tid': typeof NSlugTTidRoute
  '/n/$slug/v/$vid': typeof NSlugVVidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/inbox'
    | '/login'
    | '/profil'
    | '/search'
    | '/sitemap.xml'
    | '/n/$slug'
    | '/api/auth/$'
    | '/n/$slug/p/$pid'
    | '/n/$slug/t/$tid'
    | '/n/$slug/v/$vid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/explore'
    | '/inbox'
    | '/login'
    | '/profil'
    | '/search'
    | '/sitemap.xml'
    | '/n/$slug'
    | '/api/auth/$'
    | '/n/$slug/p/$pid'
    | '/n/$slug/t/$tid'
    | '/n/$slug/v/$vid'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/explore'
    | '/inbox'
    | '/login'
    | '/profil'
    | '/search'
    | '/sitemap.xml'
    | '/n/$slug'
    | '/api/auth/$'
    | '/n/$slug/p/$pid'
    | '/n/$slug/t/$tid'
    | '/n/$slug/v/$vid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  NSlugRoute: typeof NSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug/p/$pid': {
      id: '/n/$slug/p/$pid'
      path: '/p/$pid'
      fullPath: '/n/$slug/p/$pid'
      preLoaderRoute: typeof NSlugPPidRouteImport
      parentRoute: typeof NSlugRoute
    }
    '/n/$slug/t/$tid': {
      id: '/n/$slug/t/$tid'
      path: '/t/$tid'
      fullPath: '/n/$slug/t/$tid'
      preLoaderRoute: typeof NSlugTTidRouteImport
      parentRoute: typeof NSlugRoute
    }
    '/n/$slug/v/$vid': {
      id: '/n/$slug/v/$vid'
      path: '/v/$vid'
      fullPath: '/n/$slug/v/$vid'
      preLoaderRoute: typeof NSlugVVidRouteImport
      parentRoute: typeof NSlugRoute
    }
  }
}

interface NSlugRouteChildren {
  NSlugPPidRoute: typeof NSlugPPidRoute
  NSlugTTidRoute: typeof NSlugTTidRoute
  NSlugVVidRoute: typeof NSlugVVidRoute
}

const NSlugRouteChildren: NSlugRouteChildren = {
  NSlugPPidRoute: NSlugPPidRoute,
  NSlugTTidRoute: NSlugTTidRoute,
  NSlugVVidRoute: NSlugVVidRoute,
}

const NSlugRouteWithChildren = NSlugRoute._addFileChildren(NSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  NSlugRoute: NSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
